"""add relations

Revision ID: 0c77dba2df5f
Revises: 210305f3129e
Create Date: 2021-05-30 18:21:55.018879

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import portal


# revision identifiers, used by Alembic.
revision = '0c77dba2df5f'
down_revision = '210305f3129e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account', 'position', ['position_id'], ['id'])
    op.add_column('calendar_game', sa.Column('group_id', sa.Integer(), nullable=False))
    op.add_column('calendar_game', sa.Column('guest_team_id', sa.Integer(), nullable=False))
    op.add_column('calendar_game', sa.Column('home_team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'calendar_game', 'team', ['home_team_id'], ['id'])
    op.create_foreign_key(None, 'calendar_game', 'team', ['guest_team_id'], ['id'])
    op.create_foreign_key(None, 'calendar_game', 'group', ['group_id'], ['id'])
    op.add_column('personal_statistic', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'personal_statistic', 'account', ['account_id'], ['id'])
    op.add_column('post', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'position', ['position_id'], ['id'])
    op.add_column('standings', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'standings', 'team', ['team_id'], ['id'])
    op.add_column('team', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'team', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column('team', 'group_id')
    op.drop_constraint(None, 'standings', type_='foreignkey')
    op.drop_column('standings', 'team_id')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'position_id')
    op.drop_constraint(None, 'personal_statistic', type_='foreignkey')
    op.drop_column('personal_statistic', 'account_id')
    op.drop_constraint(None, 'calendar_game', type_='foreignkey')
    op.drop_constraint(None, 'calendar_game', type_='foreignkey')
    op.drop_constraint(None, 'calendar_game', type_='foreignkey')
    op.drop_column('calendar_game', 'home_team_id')
    op.drop_column('calendar_game', 'guest_team_id')
    op.drop_column('calendar_game', 'group_id')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'position_id')
    # ### end Alembic commands ###
