"""change relation

Revision ID: b342dba22d81
Revises: 0c77dba2df5f
Create Date: 2021-05-30 18:25:40.043213

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import portal


# revision identifiers, used by Alembic.
revision = 'b342dba22d81'
down_revision = '0c77dba2df5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('account_id', sa.Integer(), nullable=True))
    op.drop_constraint('post_position_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'account', ['account_id'], ['id'])
    op.drop_column('post', 'position_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_position_id_fkey', 'post', 'position', ['position_id'], ['id'])
    op.drop_column('post', 'account_id')
    # ### end Alembic commands ###
