"""init db

Revision ID: 210305f3129e
Revises: 
Create Date: 2021-05-30 18:20:07.463159

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import portal


# revision identifiers, used by Alembic.
revision = '210305f3129e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.Unicode(), nullable=False),
    sa.Column('email', sa.Unicode(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_player', sa.Boolean(), nullable=False),
    sa.Column('personal_number', sa.Integer(), nullable=True),
    sa.Column('date_birthday', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('registered_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('calendar_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_game', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('scores', sa.Integer(), nullable=True),
    sa.Column('penalty_min', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('short_body', sa.Text(), nullable=True),
    sa.Column('author', sa.Unicode(), nullable=True),
    sa.Column('slug', sa.Unicode(), nullable=False),
    sa.Column('is_player', sa.Boolean(), nullable=False),
    sa.Column('personal_number', sa.Integer(), nullable=True),
    sa.Column('date_birthday', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('registered_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('win_games', sa.Integer(), nullable=True),
    sa.Column('loose_games', sa.Integer(), nullable=True),
    sa.Column('scores', sa.Integer(), nullable=True),
    sa.Column('win_on_shootouts', sa.Integer(), nullable=True),
    sa.Column('loose_on_shootouts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('registered_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('standings')
    op.drop_table('post')
    op.drop_table('position')
    op.drop_table('personal_statistic')
    op.drop_table('group')
    op.drop_table('calendar_game')
    op.drop_table('account')
    # ### end Alembic commands ###
